# config.yaml

data_dir: ./data_local_test
steps: 20
batch_size: 2
sequence_length: 1024

learning_rate: 0.0004
weight_decay: 0.1
betas: [0.9, 0.95]

inference_interval: 5
inference_prompt: "The universe is "

use_small_dataset: true

# GQA parameters
n_heads: 12
n_kv_heads: 3

## LWS scaling

## Include device and type for distirbuted job


# Trainer
# if lcoal use "cpu"
device: "cpu"